project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_EX01.html"
      
        - text: "Hands-on Exercise 2"
   
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_EX02.html"
      
        - text: "Hands-on Exercise 3 Part 1"

          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_EX03_P1.html"
      
        - text: "Hands-on Exercise 3 Part 2 "
  
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_EX03_P2.html"
          
        - text: "Hands-on Exercise 4 Part 1 "
  
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_EX04_P1.html"
          
        - text: "Hands-on Exercise 4 Part 2 "
  
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_EX04_P2.html"
          
         - text: "Hands-on Exercise 4 Part 3 "
  
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_EX04_P3.html"
          
        -  text: "Hands-on Exercise 4 Part 4 "
  
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_EX04_P4.html"


          
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-Home_Ex/Take_home_Ex01.html"
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    

format:
  html:
    theme: Yeti
    css:
    - styles.css
    - box.css
    toc: true
    

editor: visual

