---
title: "Hands-on Exercise 8 Part 2"
author: "Lin Xinyue"
---

1. Prepare the data 

1.1 Install and load the packages
```{r}
pacman::p_load(sf, tmap, tidyverse)
```

1.2 Import the data
```{r}
sgpools <- read_csv("data/aspatial/SGPools_svy21.csv")
```
```{r}
list(sgpools) 
```

2. Creating a sf data frame from an aspatial data frame
```{r}
sgpools_sf <- st_as_sf(sgpools, 
                       coords = c("XCOORD", "YCOORD"),
                       crs= 3414)
```

```{r}
list(sgpools_sf)
```

3. Drawing Proportional Symbol Map
```{r}
tmap_mode("view")
```
3.1 Start with an interactive point symbol map
```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "red",
           size = 1,
           border.col = "black",
           border.lwd = 1)
```


3.2 
```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "red",
           size = "Gp1Gp2 Winnings",
           border.col = "black",
           border.lwd = 1)
```

3.3 Give it a different colour
```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "OUTLET TYPE", 
          size = "Gp1Gp2 Winnings",
          border.col = "black",
          border.lwd = 1)
```

3.4 We are twins

```{r}
tm_shape(sgpools_sf) +
  tm_bubbles(col = "OUTLET TYPE", 
          size = "Gp1Gp2 Winnings",
          border.col = "black",
          border.lwd = 1) +
  tm_facets(by= "OUTLET TYPE",
            nrow = 1,
            sync = TRUE)
```















