---
title: "In-class_Ex05a"
author: "Lin Xinyue"
---


```{r}
pacman::p_load(tidyverse, readxl,SmartEDA, easystats, gtsummary, ggstatsplot)
```

```{R}
car_resale <- read_xls("ToyotaCorolla.xls","data")

```

Summary
```{r}
car_resale %>%
  ExpData(type = 2)
```


```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin","Doors","Gears",
"Cylinders","Fuel_Type","Color",
"Met_Color", "Automatic","Mfr Guarantee","BOVAG_Guarantee","ABS","Airbag_1",
"Airbag_2","Airco","Automatic_airco","Airbag_2","Boardcomputer''CD_Player","central_Lock","powered_windows", "power_steering","Radio","stlamps","Backseat_Divider","Metallic_Rim",
"sport_ Model","Radio cassette","Tow Bar")

car_resale <- read_xls("ToyotaCorolla.xls","data")

```

```{r}
car_resale %>%
  ExpNumViz(
    target = NULL,
    nlim = 10,
    Page = c(2,2))  

```

```{r}
car_resale %>%
  ExpNumViz(
    target = "Price",
    nlim = 10,
    Page = c(2,2))  
```

Bar chart for all categro variables
```{r}
#| fig-width:12
#| fig-height:10

car_resale %>%
  ExpCatViz(
    target = NULL,
    col = "skyblue",
    clim = 10,
    margin = 2,
    Page = c(4,4),
    sample =16
  ) 


```



```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM +
              Weight + Guarantee_Period, data = 
car_resale)
model
```

```{r}

model1 <-lm(Price ~ Age_08_04 +KM +
             Weight + Guarantee_Period, data =car_resale)
check_normality(model1)           
```
```{r}
check_heteroscedasticity(model1)
```

```{r}

check_model(model1)
```

```{r}
check_collinearity(model)
```


```{r}
check_c <- check_collinearity(model)
plot(check_c)

```

```{r}
#| fig-width:12
#| fig-height:8
check_model(model1)
```


```{r}
summary(model1)
```

creat the table for professional looking
```{r}
tbl_regression (model1,
                intercept = True)
```

Can select the data want to add
```{r}
tbl_regression(model1,
               intercept =True) %>%
  agg_glance_source_note(
    label = list(sigma ~ "\U03C3"), #calculate sigma value
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value,sigma))
```


```{r}
p_model1 <- parameters(model1)
```

```{r}
plot(parameters(model1))
```

```{r}
ggcoefstats(model1,
            output = "plot")
```








                

